[package]
name = "lyon-usvg"
version = "0.1.1"
edition = "2018"
description = "Conversion between lyon and usvg"
license = "MIT"
repository = "https://github.com/jpopesculian/lyon-usvg"

[dependencies]
lyon_path = "0.17"
num-traits = "0.2"
usvg = "0.16"
